AWSTemplateFormatVersion: '2010-09-09'
Description: EKS Cluster Setup with ECR for Laravel Application Deployment, including Worker Nodes

Resources:
  # EKS Cluster Role (IAM role for EKS to interact with AWS services)
  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'eks.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: EKSClusterPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'ec2:DescribeInstances'
                  - 'ec2:DescribeSecurityGroups'
                  - 'ec2:DescribeSubnets'
                  - 'eks:DescribeCluster'
                Resource: '*'

  # EKS Cluster
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: laravel-eks-cluster
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        SubnetIds:
          - subnet-0fdc7d89e2b460ee1  # Replace with your existing subnet ID
          - subnet-0b0a0583d221d317b  # Replace with another subnet ID
        SecurityGroupIds:
          - sg-044b4b6bf5141af7f  # Replace with your existing security group ID
        EndpointPublicAccess: true  # Make the EKS API server publicly accessible

  # ECR Repository for Laravel App
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: laravel-app-repo

  # IAM Role for Worker Nodes
  EKSWorkerNodeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'ec2.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: EKSWorkerNodePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'eks:DescribeCluster'
                  - 'ec2:DescribeInstances'
                  - 'ec2:DescribeSecurityGroups'
                  - 'ec2:DescribeSubnets'
                  - 'autoscaling:DescribeAutoScalingGroups'
                  - 'autoscaling:UpdateAutoScalingGroup'
                  - 'autoscaling:DescribeLaunchConfigurations'
                Resource: '*'

  # IAM Instance Profile for Worker Nodes
  EKSWorkerNodeInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EKSWorkerNodeRole

  # Launch Template for Worker Nodes (EKS node configuration using Launch Template)
  EKSNodeGroupLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: laravel-eks-launch-template
      VersionDescription: "v1"
      LaunchTemplateData:
        ImageId: ami-0a000743ba7b9d393  # Using your specified AMI ID
        InstanceType: t3.medium
        SecurityGroupIds:
          - sg-044b4b6bf5141af7f  # Reusing existing security group
        IamInstanceProfile:
          Arn: !GetAtt EKSWorkerNodeInstanceProfile.Arn  # Correct IAM instance profile structure
        KeyName: mnk  # Using the specified EC2 KeyPair name

  # Auto Scaling Group for EKS Worker Nodes using Launch Template
  EKSNodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref EKSCluster
      NodegroupName: laravel-eks-nodegroup
      Subnets:
        - subnet-0fdc7d89e2b460ee1  # Subnet ID for node group
        - subnet-0b0a0583d221d317b  # Another subnet ID for node group
      NodeRole: !GetAtt EKSWorkerNodeRole.Arn  # IAM role for worker nodes
      ScalingConfig:
        MinSize: 1
        MaxSize: 1  # Set to 1 instance
        DesiredSize: 1  # Set to 1 instance
      LaunchTemplate:
        LaunchTemplateName: !Ref EKSNodeGroupLaunchTemplate
        Version: !GetAtt EKSNodeGroupLaunchTemplate.LatestVersionNumber
      DiskSize: 20

Outputs:
  # EKS Cluster Name
  EKSClusterName:
    Value: !Ref EKSCluster
    Description: "EKS Cluster Name"

  # URI of the ECR repository
  ECRRepositoryUri:
    Value: !GetAtt ECRRepository.RepositoryUri
    Description: "URI of the ECR repository"
