AWSTemplateFormatVersion: '2010-09-09'
Description: EKS Cluster Setup with ECR for Laravel Application Deployment, including Worker Nodes

Resources:
  # EKS Cluster Role (using an existing IAM role)
  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'eks.amazonaws.com'
            Action: 'sts:AssumeRole'

  # EKS Cluster
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: laravel-eks-cluster
      RoleArn: arn:aws:iam::650251721226:role/eksServiceRole  # Replace with your IAM role ARN
      ResourcesVpcConfig:
        SubnetIds:
          - subnet-0fdc7d89e2b460ee1  # Replace with your existing subnet ID
          - subnet-0b0a0583d221d317b  # Replace with another subnet ID
        SecurityGroupIds:
          - sg-044b4b6bf5141af7f  # Replace with your existing security group ID
        EndpointPublicAccess: true  # Make the EKS API server publicly accessible

  # ECR Repository for Laravel App
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: laravel-app-repo

  # Launch Configuration for Worker Nodes
  EKSNodeGroupLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-xxxxxxxx  # Replace with the correct EKS-optimized AMI for your region
      InstanceType: t3.medium
      SecurityGroups:
        - sg-044b4b6bf5141af7f  # Reusing existing security group
      IamInstanceProfile: arn:aws:iam::650251721226:instance-profile/EKSWorkerNodeInstanceProfile  # IAM role for worker nodes

  # Auto Scaling Group for EKS Worker Nodes
  EKSNodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref EKSCluster
      NodegroupName: laravel-eks-nodegroup
      Subnets:
        - subnet-0fdc7d89e2b460ee1  # Subnet ID for node group
        - subnet-0b0a0583d221d317b  # Another subnet ID for node group
      NodeRole: arn:aws:iam::650251721226:role/EKSWorkerNodeRole  # IAM role for worker nodes
      ScalingConfig:
        MinSize: 1
        MaxSize: 3
        DesiredSize: 2

Outputs:
  # EKS Cluster Name
  EKSClusterName:
    Value: !Ref EKSCluster
    Description: "EKS Cluster Name"

  # URI of the ECR repository
  ECRRepositoryUri:
    Value: !GetAtt ECRRepository.RepositoryUri
    Description: "URI of the ECR repository"
