Resources:
  EKSCluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: "MNKUserLoginsCluster"
      ResourcesVpcConfig:
        SubnetIds:
          - subnet-0fdc7d89e2b460ee1
          - subnet-0b0a0583d221d317b
        SecurityGroupIds:
          - sg-044b4b6bf5141af7f

  UserLoginsECR:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: "mnk-user-logins-repo"
