AWSTemplateFormatVersion: '2010-09-09'
Description: EKS Cluster with Managed Node Group and ECR setup

Parameters:
  ClusterName:
    Type: String
    Default: mnk-user-logins-cluster
    Description: Name of the EKS cluster
  NodeGroupName:
    Type: String
    Default: mnk-user-logins-node-group
    Description: Name of the EKS Node Group
  NodeInstanceType:
    Type: String
    Default: t3.medium
    Description: EC2 instance type for the nodes
  DesiredCapacity:
    Type: Number
    Default: 2
    Description: Desired number of nodes in the node group
  MinSize:
    Type: Number
    Default: 1
    Description: Minimum number of nodes in the node group
  MaxSize:
    Type: Number
    Default: 2
    Description: Maximum number of nodes in the node group
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the nodes

Resources:
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      ResourcesVpcConfig:
        SubnetIds:
          - subnet-0fdc7d89e2b460ee1
          - subnet-0b0a0583d221d317b
        SecurityGroupIds:
          - sg-044b4b6bf5141af7f
        EndpointPublicAccess: true
        EndpointPrivateAccess: false

  NodeInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      Path: /

  NodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref ClusterName
      NodegroupName: !Ref NodeGroupName
      ScalingConfig:
        MinSize: !Ref MinSize
        DesiredSize: !Ref DesiredCapacity
        MaxSize: !Ref MaxSize
      Subnets:
        - subnet-0fdc7d89e2b460ee1
        - subnet-0b0a0583d221d317b
      InstanceTypes:
        - !Ref NodeInstanceType
      AmiType: AL2_x86_64
      NodeRole: !GetAtt NodeInstanceRole.Arn

  UserLoginsECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "mnk-user-logins-repo"

Outputs:
  ClusterName:
    Description: Name of the EKS Cluster
    Value: !Ref EKSCluster

  ECRRepositoryURI:
    Description: URI of the ECR Repository
    Value: !Sub "650251721226.dkr.ecr.ap-south-1.amazonaws.com/mnk-user-logins-repo"
