apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnk-user-logins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mnk-user-logins
  template:
    metadata:
      labels:
        app: mnk-user-logins
    spec:
      containers:
        - name: mnk-user-logins
          image: <your-ecr-repo-uri>:latest
          ports:
            - containerPort: 9000
