apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnk-user-logins
  labels:
    app: mnk-user-logins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mnk-user-logins
  template:
    metadata:
      labels:
        app: mnk-user-logins
    spec:
      containers:
      - name: mnk-user-logins
        image: <IMAGE_URI>
        ports:
        - containerPort: 80
